name: VP 2017
favicon: null
layout_spectrum: 0.22024084837175906
typography_spectrum: 0.8938028151169419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2534497508313507
  lightness: 0.9221158798318356
  saturation: 0.6027190522290766
  rhythmicContrast: 0.059259464498609304
purpose: []
